<footer class="blog-footer">
    <div class="site-info">
        <span class="text-uppercase">
            v<span class="version">0.2.0</span> &copy; <span class="date">2018</span> <span class="domain">xcdh.me</span>
        </span>
        | Powered by <a class="theme-link blinky" href="//hexo.io">Hexo</a>
    </div>
    <span id="busuanzi_container_site_pv" class="stats" style="display: none;">PV: <span id="busuanzi_value_site_pv"></span>&emsp;UV: <span id="busuanzi_value_site_uv"></span></span>
</footer>
