# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Archive: /archives
  Tag: /tags

favicon: favicon/favicon.ico

stylesheets:
- /font/icon/iconfont.css
- /css/common.css

scripts:
- /font/icon/iconfont.js
- /js/utils.js
- /js/menu.js
- /js/back-to-top.js