# html lang
language: en

# main menu navigation
menu:
- url: /
  text: Home
  icon: icon-home
- url: /categories/
  text: Categories
  icon: icon-categorie
- url: /archives/
  text: Archive
  icon: icon-archive
- url: /tags/
  text: Tag
  icon: icon-tag

favicon: favicon/favicon.ico

# 你的头像url
avatar: /img/avatar.jpg
# avatar link
avatar_link: /

stylesheets:
- /css/common.css
- //cdnjs.cloudflare.com/ajax/libs/tocbot/4.1.1/tocbot.css
#- //at.alicdn.com/t/font_571373_8h84evj173z0k9.css

scripts:
- //cdnjs.cloudflare.com/ajax/libs/tocbot/4.1.1/tocbot.min.js
- /js/utils.js
- /js/menu.js
- /js/back-to-top.js
- /js/toc.js
# iconfont
- //at.alicdn.com/t/font_571373_hbwchrn0pym.js
- //cdn.bootcss.com/jquery/3.3.1/jquery.min.js
- //cdn.bootcss.com/velocity/2.0.4/velocity.min.js
# 访问量统计
- //dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js

# 是否开启toc
# toc: false
toc:
  list_number: true  # 是否显示数字排序
