# html lang
language: en

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

favicon: favicon/favicon.ico

stylesheets:
- /font/icon/iconfont.css
- /css/common.css

scripts:
- /font/icon/iconfont.js
- /js/utils.js
- /js/menu.js